### ISSUE TITLE
Doesn't work on the model from Inventor

### ISSUE THREAD

**Issue by CADBIMDeveloper** [wallabyway/nolitmaterial-ext#2]
Hi,

Do you have any suggestion, how to make something similar for the models from Inventor?

I made some research: Navisworks model materials differ from Inventor model matterials.

Inventor model materials (from `matman()._materials`) usually have something in `proteinType` property (like "Metal", "PlasticVinyl", "Generic") and all Navisworks model materials have empty string / undefined.

**Comment by wallabyway** [comment]
Hmmm, the shader code that was updated, works for Navisworks, which is basically Protein materials, which is the same non-PBR materials used in Inventor files.

So theoretically the shader update, will work across both NWD and IPT file types converted to SVF.

I haven't tested IPT yet, but I'm guessing it should be quick to see the bug, by stepping through the code and checking the MatMan object.

**Comment by wallabyway** [comment]
fixed.
